### ISSUE TITLE
RDBL crash 

### ISSUE THREAD

**Issue by duncanjovial** [ADVRHumanoids/ModelInterfaceRBDL#1]
when running with floating base = true using RDBL my module (Juan_FBcontrollers) crashes and throws the following error.

```ERROR in init_internal: model interface could not be loaded! Model joint ordering must be chain-by-chain and inside each chain joints must go from base link to tip link!```

**Comment by liesrock** [comment]
It guess it was a problem with the YAML config file: @EnricoMingo and @alaurenzi are using the floting_base=true feature without problem now.
