### ISSUE TITLE
Branch rbdl_2.6.0 not working properly 

### ISSUE THREAD

**Issue by EnricoMingo** [ADVRHumanoids/ModelInterfaceRBDL#10]
Probably due to bugged rbdl version.

**Comment by liesrock** [comment]
Ok I switched back to have v2.5.0 support in https://github.com/ADVRHumanoids/ModelInterfaceRBDL/commit/c223dab0db2def34039ee9ea00c4910b86b5b371

I will also fix the rbdl version to v2.5.0 on the superbuild
