### ISSUE TITLE
Building problem: RBDL version should be v2.5

### ISSUE THREAD

**Issue by DavideAntonucci** [ADVRHumanoids/ModelInterfaceRBDL#12]
Hi all,

I found this problem during the building phase of the ModelInterfaceRBDL:

![image](https://user-images.githubusercontent.com/55489504/77306203-9aea7500-6cf7-11ea-95c0-6b7bfb03bfaa.png)

I think that is related on RBDL library version but I'm not sure.

Any clue?

Davide.

**Comment by liesrock** [comment]
thanks @DavideAntonucci ! Can you check the version of RBDL in use?

Something like this:

```
cd $XBOT_ROOT/external/rbdl
```

and check the branch/tag.

**Comment by DavideAntonucci** [comment]
Hi @liesrock,

this is the branch/tag:

~/MultiDoF-superbuild/external/rbdl ((HEAD detached at v2.6.0))

Davide.

**Comment by liesrock** [comment]
Thanks @DavideAntonucci I am testing the issue and try to reproduce it on my pc.

**Comment by liesrock** [comment]
I can reproduce the issue: I changed the rbdl to v2.6, but the correct one is v2.5.

Thanks a lot for spotting this @DavideAntonucci: I fixed it on this commit https://github.com/ADVRHumanoids/MultiDoF-superbuild/commit/87e25b8aa3ffc56d3676068616e11e70ea6212af on the MultiDoF-superbuild.

Moreover you can have the compilation back to work by:

```
cd $XBOT_ROOT/external/rbdl
git checkout v2.5.0 
cd ../../build
make rbdl
make ModelInterfaceRBDL
```

**Comment by DavideAntonucci** [comment]
Thank you @liesrock, done!
Davide.
