### ISSUE TITLE
Update API to last RBDL master

### ISSUE THREAD

**Issue by EnricoMingo** [ADVRHumanoids/ModelInterfaceRBDL#5]
As title, if simple should be nicec to update to last version of RBDL master.

**Comment by liesrock** [comment]
Can you specify the git TAG? I can update it if needed

**Comment by liesrock** [comment]
I worked on this and I suggest to use rbdl version 2.6.0 (https://rbdl.bitbucket.io/d8/d59/api_version_checking_page.html).

I modified our ModelInterfaceRBDL accordingly (https://github.com/ADVRHumanoids/ModelInterfaceRBDL/commit/789cd2fd595d7a811bf862415f4e343559e4e20c): I will open a pull request to @alaurenzi

**Comment by liesrock** [comment]
Done in the PR https://github.com/ADVRHumanoids/ModelInterfaceRBDL/pull/9

**Comment by liesrock** [comment]
Because of the described bug we should use this version (https://bitbucket.org/rbdl/rbdl/commits/338e4db)
